use_frameworks!

target 'UIViewDidAppear_Example' do
  pod 'UIViewDidAppear', :path => '../'

  target 'UIViewDidAppear_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
